### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by josephrocca** [zanussbaum/surfgrad#8]
Very cool project! Next up: JAX.js 😁

Also wanted to give you a heads up that the link to this repo in your announcement tweet is broken, so you may be getting fewer stars than you otherwise would have.

**Comment by zanussbaum** [comment]
thank you so much!

and thanks for the heads up! X doesn't let me update the link :/ 

I [quote tweeted](https://x.com/zach_nussbaum/status/1856099870324535476) but probably won't reach the same audience 🤷
